version: '3'
services:
  patroni_etcd:
    container_name: patroni_etcd
    image: patroni
    command: --etcd
#    networks:
#      - pg_cluster
  
  patroni_etcd1:
    container_name: patroni_etcd1
    image: patroni
    command: --etcd
#    networks:
#      - pg_cluster

  pg_ressel_node:
    image: patroni
#    hostname: dbnode2
    links:
        - patroni_etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_URL: http://patroni_etcd:2379
        PATRONI_ETCD_URL: http://patroni_etcd1:2379
        PATRONI_NAME: dbnode2
        PATRONI_SCOPE: resell_pg
  pg_ressel_node1:
    image: patroni
#    hostname: dbnode2
    links:
        - patroni_etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_URL: http://patroni_etcd:2379
        PATRONI_ETCD_URL: http://patroni_etcd1:2379
        PATRONI_NAME: dbnode2
        PATRONI_SCOPE: resell_pg
#    networks:
#      - pg_cluster

  pg_ressel_node:
    image: patroni
#    hostname: dbnode2
    links:
        - patroni_etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_URL: http://patroni_etcd:2379
        PATRONI_ETCD_URL: http://patroni_etcd1:2379
        PATRONI_NAME: dbnode2
        PATRONI_SCOPE: resell_pg

  haproxy:
    image: patroni
    links:
        - patroni_etcd:patroni_etcd
        - patroni_etcd:patroni_etcd1
    ports:
        - "5000:5000"
        - "5001:5001"
    environment:
        PATRONI_ETCD_URL: http://patroni_etcd1:2379
        PATRONI_ETCD_URL: http://patroni_etcd:2379
        PATRONI_SCOPE: resell_pg
    command: --confd
#    networks:
#      - pg_cluster
#networks:
#  pg_cluster:
#     external: true
