version: '3'
services:
  etcd1:
    container_name: etcd1
    image: patroni
    hostname: etcd1
    command: --etcd 

  etcd2:
    container_name: etcd2
    image: patroni
    hostname: etcd2
    command: --etcd 

  pg_ressel_node:
    image: patroni
#    hostname: dbnode2
    links:
        - patroni_etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_URL: http://etcd1:2379
        PATRONI_NAME: dbnode
        PATRONI_SCOPE: resell_pg

    deploy:
        mode: global


  pg_ressel_node1:
    image: patroni
#    hostname: dbnode2
    links:
        - patroni_etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_URL: http://etcd1:2379
        PATRONI_NAME: dbnode1
        PATRONI_SCOPE: resell_pg
    deploy:
        mode: global



  pg_ressel_node2:
    image: patroni
#    hostname: dbnode2
    links:
        - patroni_etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_URL: http://etcd1:2379
        PATRONI_NAME: dbnode2
        PATRONI_SCOPE: resell_pg
    deploy:
        mode: global

  haproxy:
    image: patroni
    links:
        - patroni_etcd:patroni_etcd
    ports:
        - "5000:5000"
        - "5001:5001"
    environment:
        PATRONI_ETCD_URL: http://etcd1:2379
        PATRONI_SCOPE: resell_pg
    command: --confd
    deploy:
        mode: global
