version: '3'
services:
  etcd1:
    container_name: etcd1
    image: patroni
    command: --etcd \
      --advertise-client-urls=http://etcd1:2379,http://etcd1:4001 \
      --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001 \
      --initial-advertise-peer-urls=http://etcd2:2380 \
      --listen-peer-urls=http://0.0.0.0:2380 \
      --initial-cluster-token=9489bf68bdfe1b9ae037d6fd9e7efefd \
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380 \
      --initial-cluster-state=new \
      --auto-tls \
      --peer-auto-tls \
      --data-dir=/var/lib/etcd

  etcd2:
    container_name: etcd2
    image: patroni
    command: --etcd \
      --advertise-client-urls=http://etcd2:2379,http://etcd2:4001 \
      --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001 \
      --initial-advertise-peer-urls=http://etcd2:2380 \
      --listen-peer-urls=http://0.0.0.0:2380 \
      --initial-cluster-token=9489bf68bdfe1b9ae037d6fd9e7efefd \
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380 \
      --initial-cluster-state=new \
      --auto-tls \
      --peer-auto-tls \
      --data-dir=/var/lib/etcd

  pg_ressel_node:
    image: patroni
#    hostname: dbnode2
    links:
        - patroni_etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_URL: http://patroni_etcd:2379
        PATRONI_NAME: dbnode2
        PATRONI_SCOPE: resell_pg

    deploy:
        mode: global


  pg_ressel_node1:
    image: patroni
#    hostname: dbnode2
    links:
        - patroni_etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_URL: http://patroni_etcd:2379,http://patroni_etcd1:2379
        PATRONI_NAME: dbnode2
        PATRONI_SCOPE: resell_pg
    deploy:
        mode: global



  pg_ressel_node2:
    image: patroni
#    hostname: dbnode2
    links:
        - patroni_etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_URL: http://patroni_etcd:2379,http://patroni_etcd1:2379
        PATRONI_NAME: dbnode2
        PATRONI_SCOPE: resell_pg
    deploy:
        mode: global

  haproxy:
    image: patroni
    links:
        - patroni_etcd:patroni_etcd
    ports:
        - "5000:5000"
        - "5001:5001"
    environment:
        PATRONI_ETCD_URL: http://patroni_etcd:2379,http://patroni_etcd1:2379
        PATRONI_SCOPE: resell_pg
    command: --confd
    deploy:
        mode: global
