
version: '3'
services:
   etcd1:
    image: quay.io/coreos/etcd
    ports:
      - 2379
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd1
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd1:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd1:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
  etcd2:
    image: quay.io/coreos/etcd
    ports:
      - 2379
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd1
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd2:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd2:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd1=http://etcd1:2380,etcd2=http://etcd2:2380

  pg_ressel_node:
    image: patroni
#    hostname: dbnode2
    links:
        - patroni_etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_URL: http://etcd1:2379
        PATRONI_NAME: dbnode
        PATRONI_SCOPE: resell_pg

    deploy:
        mode: global


  pg_ressel_node1:
    image: patroni
#    hostname: dbnode2
    links:
        - patroni_etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_URL: http://etcd1:2379
        PATRONI_NAME: dbnode1
        PATRONI_SCOPE: resell_pg
    deploy:
        mode: global



  pg_ressel_node2:
    image: patroni
#    hostname: dbnode2
    links:
        - patroni_etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_HOSTS: etcd1:2379,etcd2:2379
        PATRONI_NAME: dbnode2
        PATRONI_SCOPE: resell_pg
    deploy:
        mode: global

  haproxy:
    image: patroni
    links:
        - patroni_etcd:patroni_etcd
    ports:
        - "5000:5000"
        - "5001:5001"
    environment:
#        PATRONI_ETCD_URL: http://etcd1:2379
#        PATRONI_ETCD_URL1: http://etcd1:2379
        PATRONI_SCOPE: resell_pg
    command: --confd
    deploy:
        mode: global
